# Generated by Django 3.1.6 on 2021-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('ability_1', models.CharField(max_length=20)),
                ('ability_2', models.CharField(max_length=20)),
                ('category_1', models.CharField(max_length=20)),
                ('category_2', models.CharField(max_length=20)),
                ('img', models.FilePathField()),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
