# Generated by Django 3.1.6 on 2021-02-18 20:14

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Pokemon = apps.get_model("pokedex", "Pokemon")
        for instance in Pokemon.objects.all():
            if not instance.slug:
                instance.slug = slugify(instance.name)
                instance.save()

    def reverse_func(apps, schema_editor):
        pass

    dependencies = [
        ('pokedex', '0002_auto_20210218_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(
            forwards_func, reverse_func
            )
    ]
