# Generated by Django 3.1.6 on 2021-02-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ability_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='category_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='img',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
