# Generated by Django 3.1.6 on 2021-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_comment_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date']},
        ),
    ]
